name: Build and Publish NuGet Package

on:
  push:
    branches: [ master ]
    paths:
      - 'GHttpHelper/**'
      - '.github/workflows/publish-nuget.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ICU
        run: sudo apt-get update && sudo apt-get install -y libicu-dev

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.0.x'  # 使用 .NET Standard 2.0

      - name: Restore dependencies
        run: dotnet restore ./GHttpHelper/GHttpHelper.csproj

      - name: Pack NuGet package
        run: dotnet pack ./GHttpHelper/GHttpHelper.csproj --configuration Release --output ./nupkgs

      - name: Publish NuGet package
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json