name: Build and Publish NuGet Package

on:
  push:
    branches: [ master ]
    paths:
      - 'GHttpHelper/**'
      - '.github/workflows/publish-nuget.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish in Docker
        uses: docker://mcr.microsoft.com/dotnet/sdk:2.0
        with:
          args: |
            bash -c "
            apt-get update && apt-get install -y libicu-dev &&
            dotnet restore ./GHttpHelper/GHttpHelper.csproj &&
            dotnet pack ./GHttpHelper/GHttpHelper.csproj --configuration Release --output ./nupkgs &&
            dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
            "